export const vocabularyBooks = [
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774252/vocab_1_axjltv.png",
    name: "4000 Essential English Words Book 1",
    word_count: 600,
    units: [
      { id: 1, title: "The Lion and the Rabbit"},
      { id: 2, title: "The Laboratory" },
      { id: 3, title: "The Report" },
      { id: 4, title: "The Dog’s Bell" },
      { id: 5, title: "The Jackal and the Sun Child" },
      { id: 6, title: "The Friendly Ghost" },
      { id: 7, title: "The Best Prince" },
      { id: 8, title: "How the Sun and the Moon Were Made" },
      { id: 9, title: "The Starfish" },
      { id: 10, title: "The First Peacock" },
      { id: 11, title: "Princess Rose and the Creature" },
      { id: 12, title: "The Crazy Artist" },
      { id: 13, title: "The Farmer and the Cats" },
      { id: 14, title: "A Magical Book" },
      { id: 15, title: "The Big Race" },
      { id: 16, title: "Adams County’s Gold" },
      { id: 17, title: "The Race for Water" },
      { id: 18, title: "The Little Red Chicken" },
      { id: 19, title: "Shipwrecked" },
      { id: 20, title: "The Seven Cities of Gold" },
      { id: 21, title: "Katy" },
      { id: 22, title: "A Better Reward" },
      { id: 23, title: "The Camp" },
      { id: 24, title: "A Strong Friendship" },
      { id: 25, title: "Joe’s Pond" },
      { id: 26, title: "Archie and His Donkey" },
      { id: 27, title: "The Spider and the Bird" },
      { id: 28, title: "The Party" },
      { id: 29, title: "How the World Got Light" },
      { id: 30, title: "Cats and Secrets" },
    ],
  },
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774253/vocab-2_zpuyp9.png",
    name: "4000 Essential English Words Book 2",
    word_count: 600,
    units: [
      { id: 1, title: "The Twelve Months" },
      { id: 2, title: "The Dragon" },
      { id: 3, title: "The Battle of Thermopylae" },
      { id: 4, title: "The Deer and His Image" },
      { id: 5, title: "May 29,1953" },
      { id: 6, title: "The Frog Prince" },
      { id: 7, title: "A Beautiful Bird" },
      { id: 8, title: "Tricky Turtle" },
      { id: 9, title: "The Tale of Bartelby O'Boyle" },
      { id: 10, title: "Blackbeard" },
      { id: 11, title: "Dinosaur Drawings" },
      { id: 12, title: "The Mean Chef" },
      { id: 13, title: "The Cat and the Fox" },
      { id: 14, title: "The Good Student" },
      { id: 15, title: "The Lucky Knife" },
      { id: 16, title: "Prince Sam" },
      { id: 17, title: "Henry Ford's Famous Car" },
      { id: 18, title: "The Priest" },
      { id: 19, title: "Mrs. May and the Green Girl" },
      { id: 20, title: "Albert Einstein" },
      { id: 21, title: "From the Earth to the Stars" },
      { id: 22, title: "The Farm Festival" },
      { id: 23, title: "The Clever Thief" },
      { id: 24, title: "The Doctor's Cure" },
      { id: 25, title: "The Criminal" },
      { id: 26, title: "The Two Captains" },
      { id: 27, title: "The Duke and the Minister" },
      { id: 28, title: "The Fisherman" },
      { id: 29, title: "Osiris and the Nile" },
      { id: 30, title: "The Taxi Driver" }
    ],
  },
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774252/vocab_3_gt3hcu.png",
    name: "4000 Essential English Words Book 3",
    word_count: 600,
    units: [
      { id: 1, title: "The Real St. Nick" },
      { id: 2, title: "The Shepherd and the Wild Sheep" },
      { id: 3, title: "The Boy and his Sled" },
      { id: 4, title: "Tiny Tina" },
      { id: 5, title: "Trick-or-treat!" },
      { id: 6, title: "The Senator and the Worm" },
      { id: 7, title: "Patsy Ann" },
      { id: 8, title: "The Anniversary Gift" },
      { id: 9, title: "Dalton vs. the Bully" },
      { id: 10, title: "Anna the Babysitter" },
      { id: 11, title: "Peter and the Dwarf" },
      { id: 12, title: "The Ice Cream Cone Explosion" },
      { id: 13, title: "Sheriff Dan" },
      { id: 14, title: "The Helpful Apprentice" },
      { id: 15, title: "Why Monkey Has No Home" },
      { id: 16, title: "Matthew Learns a Lesson" },
      { id: 17, title: "The Magic Cup" },
      { id: 18, title: "The Knight's Plan" },
      { id: 19, title: "The Magic Pear Tree" },
      { id: 20, title: "Little Wolf and Mother Wolf" },
      { id: 21, title: "The Old Man with a Bump" },
      { id: 22, title: "The Circus" },
      { id: 23, title: "Lazy Hans" },
      { id: 24, title: "The Bremen Town Musicians" },
      { id: 25, title: "How Did Greenland Get Its Name?" },
      { id: 26, title: "Everyone is Special" },
      { id: 27, title: "Pizarro and the Inca Gold" },
      { id: 28, title: "The Boy Who Saved the Town" },
      { id: 29, title: "An Interesting Life" },
      { id: 30, title: "The Kitten and the Caterpillar" }
    ],
  },
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774253/vocab_4_dujqob.png",
    name: "4000 Essential English Words Book 4",
    word_count: 600,
    units: [
      { id: 1, title: "The History of Chocolate" },
      { id: 2, title: "Monkey Island" },
      { id: 3, title: "The Young Man and the Old Man" },
      { id: 4, title: "The Tricky Fox" },
      { id: 5, title: "The Magic Computer" },
      { id: 6, title: "Jack Frost and the Pudding" },
      { id: 7, title: "The Architect's Plan" },
      { id: 8, title: "Janie and the Music Player" },
      { id: 9, title: "Growing to be Great" },
      { id: 10, title: "Anton's Great Discovery" },
      { id: 11, title: "How a Singer Helped Win the War" },
      { id: 12, title: "The Sun and the North Wind" },
      { id: 13, title: "The Big Race" },
      { id: 14, title: "The Brothers and the Bread" },
      { id: 15, title: "Laika, the Space Dog" },
      { id: 16, title: "Gwen's New Friends" },
      { id: 17, title: "Kara Goes Camping" },
      { id: 18, title: "The School Play" },
      { id: 19, title: "Isaac's First Plane Trip" },
      { id: 20, title: "The Betrayal" },
      { id: 21, title: "The Teller and the Thieves" },
      { id: 22, title: "The Scribe's Warning" },
      { id: 23, title: "How the Dinosaurs Really Died" },
      { id: 24, title: "The Traveler and the Innkeeper" },
      { id: 25, title: "Gilbert and the Lizard" },
      { id: 26, title: "The Forest People" },
      { id: 27, title: "a Dying Forest" },
      { id: 28, title: "Thucydides and the Plague of Athens" },
      { id: 29, title: "The Solar Car Race" },
      { id: 30, title: "The Heirs" }
    ],
  },
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774252/vocab_5_uxrn7b.png",
    name: "4000 Essential English Words Book 5",
    word_count: 600,
    units: [
      { id: 1, title: "The Little Mice" },
      { id: 2, title: "The Helpful Abbey" },
      { id: 3, title: "The Bachelor's Lesson" },
      { id: 4, title: "The Corrupt Administrator" },
      { id: 5, title: "a Famous Accident" },
      { id: 6, title: "The Island" },
      { id: 7, title: "Small World" },
      { id: 8, title: "Becoming a Healer" },
      { id: 9, title: "The Weaving Machine" },
      { id: 10, title: "Life on the Farm" },
      { id: 11, title: "Beethoven's Gift" },
      { id: 12, title: "Brothers" },
      { id: 13, title: "The Old Hound" },
      { id: 14, title: "Day Without Sight" },
      { id: 15, title: "The Big Ship" },
      { id: 16, title: "The History of Parachutes" },
      { id: 17, title: "“I Didn't Do It!”" },
      { id: 18, title: "The Soldier's Decision" },
      { id: 19, title: "Jane's Pride" },
      { id: 20, title: "Microchips" },
      { id: 21, title: "The Twins" },
      { id: 22, title: "The New Bioco" },
      { id: 23, title: "How Comet Got His Tail" },
      { id: 24, title: "The Resourceful Landlord" },
      { id: 25, title: "The Man and the Monkey" },
      { id: 26, title: "Cosmo's Flight" },
      { id: 27, title: "The First Organ Transplant" },
      { id: 28, title: "The Lottery" },
      { id: 29, title: "Jen's New Job" },
      { id: 30, title: "The Demon's Bridge" }
    ],
  },
  {
    image_link: "https://res.cloudinary.com/dalaaegob/image/upload/v1769774254/vocab_6_rf9ub1.png",
    name: "4000 Essential English Words Book 6",
    word_count: 600,
    units: [
      { id: 1, title: "The North Star" },
      { id: 2, title: "The Fossil Hunters" },
      { id: 3, title: "Dressed to Excess" },
      { id: 4, title: "The Butler's Bad Day" },
      { id: 5, title: "A Bet" },
      { id: 6, title: "Amazing Komodo Dragons" },
      { id: 7, title: "Greek Magical Papyri" },
      { id: 8, title: "Watch Out!" },
      { id: 9, title: "Dangerous Bites" },
      { id: 10, title: "The Avalanche" },
      { id: 11, title: "The Lydian King" },
      { id: 12, title: "The Butler" },
      { id: 13, title: "The End of Smallpox" },
      { id: 14, title: "The Coward's Lesson" },
      { id: 15, title: "Epidemic in Zimbabwe" },
      { id: 16, title: "The Brute and the Billionaire" },
      { id: 17, title: "The Tenacious Inventor" },
      { id: 18, title: "The Nurse's Lesson" },
      { id: 19, title: "Seizures Then and Now" },
      { id: 20, title: "The Greedy Bee" },
      { id: 21, title: "The Mayor of Sherman" },
      { id: 22, title: "The Editor's Choice" },
      { id: 23, title: "The Ice House" },
      { id: 24, title: "Preparing of the Future" },
      { id: 25, title: "Hundred Plays" },
      { id: 26, title: "The Kidnapping" },
      { id: 27, title: "The Earl of Shining" },
      { id: 28, title: "The Lord and the Farmers" },
      { id: 29, title: "The Shortcut" },
      { id: 30, title: "The Mad Hatter" }
    ],
  },
];